var InstrumentEditor = (function () {
    function InstrumentEditor() {
        this.x = 0;
        var mainWindow = new MainWidget();
        this.w = new TabWidget(mainWindow);
        this.w.AddTab("Визуальный редактор");
        this.w.AddTab("Редактор логики");
        this.w.AddTab("Общие настройки");
        var w = new Widget();
        var w2 = new Widget();
        this.w.AddWidgetOnTab(0, w);
        this.w.AddWidgetOnTab(0, w2);
        w.Width = 77;
        w2.Width = 23;
        var tab = new TabWidget(w2);
        tab.AddTab("Элементы");
        tab.AddTab("Свойства");
        tab.AddTab("Инспектор");
        var itemWidget = new ItemListWidget();
        itemWidget.CreateNewItem("dsfsdf");
        itemWidget.CreateNewItem("dsfsdf");
        itemWidget.CreateNewItem("dsfsdf");
        itemWidget.CreateNewItem("dsfsdf");
        tab.AddWidgetOnTab(0, itemWidget);
        var w22 = new Widget();
        w22.Text = "sdfsdf";
        tab.AddWidgetOnTab(1, w22);
        var toolBar = new ToolBarWidget(w);
        toolBar.Height = 5;
        toolBar.AddToolGroup();
        toolBar.AddToolGroup();
        toolBar.ToolGroup[0].AddButton();
        toolBar.ToolGroup[0].AddButton();
        toolBar.ToolGroup[0].AddButton();
        toolBar.ToolGroup[1].AddButton();
        toolBar.ToolGroup[1].AddButton();
        toolBar.ToolGroup[1].AddButton();
        var canvas = new Widget();
        canvas.DomElement.id = "main_canvas_container";
        canvas.Height = 95;
        canvas.DomElement.style.backgroundColor = "#c5c5c5";
        w.AddChildWidget(canvas);
        this.w.Height = 100;
        blend4WebEngine.Init();
        toolBar.AddToolGroup(new TransformMenu());
    }
    return InstrumentEditor;
}());
var instrumentEditor = new InstrumentEditor();
